### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-kubernetes-visualizer#4]
A screenshot or a link to a screenshot would be awesome!

**Comment by madhana** [comment]
![azurekubevisualizer-3](https://cloud.githubusercontent.com/assets/8301387/4307446/6ac6daf0-3e89-11e4-96e9-92898bc4d91f.png)

**Comment by ahmetb** [comment]
That'd look better in the README. Thanks. :-)
